"""initial

Revision ID: 9b882b1cbd0c
Revises: 
Create Date: 2026-01-29 05:58:21.588523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b882b1cbd0c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('b_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('b_id')
    )
    op.create_table('payments',
    sa.Column('p_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('p_id')
    )
    op.create_table('stations',
    sa.Column('s_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('prefix', sa.Integer(), nullable=False),
    sa.Column('last_number', sa.Integer(), nullable=True),
    sa.Column('last_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('s_id')
    )
    op.create_table('tickets',
    sa.Column('t_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('dep_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('p_id', sa.Integer(), nullable=False),
    sa.Column('b_id', sa.Integer(), nullable=False),
    sa.Column('s_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['b_id'], ['businesses.b_id'], ),
    sa.ForeignKeyConstraint(['p_id'], ['payments.p_id'], ),
    sa.ForeignKeyConstraint(['s_id'], ['stations.s_id'], ),
    sa.PrimaryKeyConstraint('t_id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('options',
    sa.Column('o_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('dep_st', sa.String(length=50), nullable=False),
    sa.Column('arr_st', sa.String(length=50), nullable=False),
    sa.Column('adults', sa.Integer(), nullable=True),
    sa.Column('childs', sa.Integer(), nullable=True),
    sa.Column('dep_or_arr', sa.Boolean(), nullable=False),
    sa.Column('preferred_time', sa.Time(), nullable=True),
    sa.Column('preference', sa.String(length=200), nullable=True),
    sa.Column('t_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['t_id'], ['tickets.t_id'], ),
    sa.PrimaryKeyConstraint('o_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('options')
    op.drop_table('tickets')
    op.drop_table('stations')
    op.drop_table('payments')
    op.drop_table('businesses')
    # ### end Alembic commands ###
